### ISSUE TITLE
Doesn't work with support library

### ISSUE THREAD

**Issue by verbeeckjan** [mikepenz/Android-ActionItemBadge#11]
I'm using the android.support.v7 library, this means that when I do 'menu.findItem(R.id.item_samplebadge)', I get an object with the  'android.support.v7.internal.view.menu.MenuItemImpl' class. This class doesn't support getActionView() method. This means the library throws the following error:

```java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
            at com.mikepenz.actionitembadge.library.ActionItemBadge.update(ActionItemBadge.java:199)```

Is there anything I can do so it will work with the support library?

**Comment by mikepenz** [comment]
The sample also uses the support v7 actionbar:

https://github.com/mikepenz/Android-ActionItemBadge/blob/master/app/src/main/java/com/mikepenz/actionitembadge/sample/MainActivity.java

and the menu.xml used in the sample:

https://github.com/mikepenz/Android-ActionItemBadge/blob/master/app/src/main/res/menu/main.xml

**Comment by verbeeckjan** [comment]
I found the problem! I used android:actionLayout="@layout/menu_badge" in the xml. This should yourapp:actionLayout="@layout/menu_badge". It's right in the example but you might want to adjust it in the documentation. Thanks for the quick reply!

**Comment by mikepenz** [comment]
@verbeeckjan docu fixed. thanks.
