### ISSUE TITLE
Library not working with Maven  - proposed solution

### ISSUE THREAD

**Issue by athkalia** [mikepenz/Android-ActionItemBadge#12]
Hello, 

seems like your pom.xml is missing something to make this library work with maven-android-plugin

specifically, you should change your dependency inside your pom.xml to be:

     <dependency>
          <groupId>com.mikepenz.iconics</groupId>
          <artifactId>library</artifactId>
          <type>aar</type>
          <version>0.7.0</version>
          <scope>compile</scope>
        </dependency>

(i just added the "type" part)
Thanks

**Comment by mikepenz** [comment]
@athkalia this library does not contain a pom.xml. It's just tested as gradle dependency with Android Studio.

You probably created it by yourself?

**Comment by athkalia** [comment]
I have never used gradle so I can't help you all that much, (unless you are no expert either, in that case I'll just spend a day and figure it out). Basically it goes like this:

In order to publish your library in maven central you need a pom.xml
This has been generated automatically for you by a maven-gradle plugin that you have in your files (search your repository for the word "maven").
Unfortunately there's one line missing from that generated pom.xml, the one i specified at the beginning.
Without that line, maven doesn't know which artifact to download for the dependency that this library has 
http://search.maven.org/#artifactdetails%7Ccom.mikepenz.iconics%7Clibrary%7C0.7.1%7Caar

as there are multiple files, and maven doesn't know which one to download. If you look at the bottom on the link i sent you, there's jar files etc in there as well as .aar. Gradle probably has a way of picking one, so it works for gradle but fails for maven.

As I am no gradle expert, a solution may be to insert a "@aar" right after the dependency in build.gradle, but I read that it may get deprecated or something, so it may not be the correct solution.

so change "    compile 'com.mikepenz.iconics:library:0.7.0'" to     compile 'com.mikepenz.iconics:library:0.7.0@aar' in your library/build.gradle

Does this make any sense to you ?

**Comment by mikepenz** [comment]
@athkalia i use gradle in all my projects and it got default to add the **@aar** at the end of all my dependency. never thought of it as an extra step because some libraries are published wrong. 

but with your description i know what you try to say with this issue. 

I will see if i can somewhere specify this in my maven release plugin. would be strange if i couldn't. thanks for your input ;)

I'll let you know if i find the solution how you can define this within a gradle maven publish :dancer:

**Comment by athkalia** [comment]
Thanks a lot, please do keep me posted : )

**Comment by mikepenz** [comment]
@athkalia seems this isn't as trivial as it should be. 

the official maven plugin for gradle doesn't allow to set the type. 
i set the packaging as .aar but this is not the solution (because i did it since the first release @ maven central)
