### ISSUE TITLE
Cannot add badge for style with layout

### ISSUE THREAD

**Issue by willowcheng** [mikepenz/Android-ActionItemBadge#13]
I meet the drawable parameter problem with this line:
``` java
ActionItemBadge.update(this, menu.findItem(R.id.item_samplebadge), Iconify.IconValue.fa_android, ActionItemBadge.BadgeStyle.DARKGREY, badgeCount);
```

Then I replace `Iconify.IconValue.fa_android` with `new IconDrawable(this, Iconify.IconValue.fa_android)`. 

However, I still face the problem and console shows that:

 java.lang.NullPointerException for `update` method in `onCreateOptionsMenu`

**Comment by mikepenz** [comment]
@willowcheng what's the version you use? 
I think i have to update the README. the newest version uses the Iconics library. Please see the sample for more details.
