### ISSUE TITLE
ActionItemBadge working with Toolbar?

### ISSUE THREAD

**Issue by finberg** [mikepenz/Android-ActionItemBadge#16]
Hello!
ActionItemBadge working with Toolbar?

**Comment by mikepenz** [comment]
@finberg just use it as you would with an actionbar. There is no difference at all.

**Comment by finberg** [comment]
Thanks you!

**Comment by qzaqza1818** [comment]
Hi ! Sorry but I am not seeing any sample with a toolbar activity but only action bar. Am I missing something?

**Comment by qzaqza1818** [comment]
Silly me, I had found the sample with toolbar activity.
