### ISSUE TITLE
Badge in hamburger icon

### ISSUE THREAD

**Issue by anticafe** [mikepenz/Android-ActionItemBadge#21]
I see in some Chinese app, they often add a "red dot" into tab or hamburger icon. For example in [this article](http://dangrover.com/blog/2014/12/01/chinese-mobile-app-ui-trends.html). In below image, there is a similar "red dot" but not in hamburger.

![image](https://cloud.githubusercontent.com/assets/340836/8729250/4ba17a30-2c14-11e5-93f8-4e46f0897bfd.png)

So, is it possible to add such "red dot" into hamburger icon?

**Comment by mikepenz** [comment]
@anticafe no this is not possible. this library is only meant to add this badge to ActionItems
