### ISSUE TITLE
Update Badge Value Dynamically

### ISSUE THREAD

**Issue by cliffgr** [mikepenz/Android-ActionItemBadge#24]
I want update my badge when my async finish succesfuly.

**Comment by mikepenz** [comment]
Everything shown in the sample. Just call `invalidateOptionsMenu()` in order to refresh the items (also the badge)

https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/app/src/main/java/com/mikepenz/actionitembadge/sample/ToolbarActivity.java#L109
