### ISSUE TITLE
How do I set a custom color for the badge?

### ISSUE THREAD

**Issue by confile** [mikepenz/Android-ActionItemBadge#29]
How do I set a custom color for the badge?

**Comment by mikepenz** [comment]
@confile look at the sample application. it shows how you can use the `BadgeStyle`

https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/app/src/main/java/com/mikepenz/actionitembadge/sample/ToolbarActivity.java

**Comment by confile** [comment]
Thanks
