### ISSUE TITLE
How can I change the position of the badge?

### ISSUE THREAD

**Issue by confile** [mikepenz/Android-ActionItemBadge#30]
How can I change the position of the badge?

**Comment by mikepenz** [comment]
@confile can you be a bit more specific? 

You can provide a custom layout for a custom `BadgeStyle` https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/java/com/mikepenz/actionitembadge/library/utils/BadgeStyle.java#L85

This layout should be similar to this one: https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/res/layout/menu_badge.xml 

You can then just modify the positioning of the badge (the `TextView`)

**Comment by confile** [comment]
Thanks

**Comment by confile** [comment]
Works great!
