### ISSUE TITLE
Issue regarding to tablayout

### ISSUE THREAD

**Issue by qzaqza1818** [mikepenz/Android-ActionItemBadge#37]
I have saw samples that work with actionbar and toolbar, but what about the tablayout ? 
Besides, I used viewpager to add fragment. 
![capture2](https://cloud.githubusercontent.com/assets/15046075/11550456/0c3f6e38-99ab-11e5-9003-e5a5c6cdad25.PNG)

**Comment by mikepenz** [comment]
@qzaqza1818 so what's your question?

**Comment by qzaqza1818** [comment]
My question is after I set custom view for a tab(Friend), what should I do next?
Because for this library https://github.com/jgilfelt/android-viewbadger, I can call 
```
View v = getActionBar().getTabAt(0).getCustomView();
            BadgeView badge = new BadgeView(getActivity(), v);
            badge.setText("1");
            badge.show();
```
but I don't know how to do the same with your library. Sorry for poor grammar.
![capture3](https://cloud.githubusercontent.com/assets/15046075/11555820/e727b6a4-99dd-11e5-9d3a-07d7ce207fcf.PNG)

**Comment by mikepenz** [comment]
@qzaqza1818 this library can only be used to add badges in `MenuItem`s of a `Toolbar` or `Actvitiy`.

**Comment by qzaqza1818** [comment]
oh I see thank you.
