### ISSUE TITLE
Ambiguous Method Call 

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/Android-ActionItemBadge#39]
![error](https://cloud.githubusercontent.com/assets/6092323/12412123/5f120c46-beaa-11e5-905a-2df57e3b7cb7.png)

I want to use only BadgeLarge in Toolbar & want to update it's BadgeCount dynamically in my Activity

**Comment by mikepenz** [comment]
@patelakshay13890 the problem is that you pass `null` as the third param. So java does not know which type this is. `null` is neither an `IIcon` nor a `Drawable`. Replace `null` with `(Drawable) null` or `(IIcon) null`
