### ISSUE TITLE
Make it round

### ISSUE THREAD

**Issue by Mathbl** [mikepenz/Android-ActionItemBadge#40]
Would it be possible to make the badge a perfect circle when there's only one number? Thanks.

**Comment by mikepenz** [comment]
@Mathbl you can define a corner on the `BadgeStyle` you can provide. If the corner is half of the full width the badge will be a circle

**Comment by Mathbl** [comment]
Yes, I created my own menu_badge layout and put a minWidth. That way, setting the corner value did the trick.

Thanks and good job on the library.
