### ISSUE TITLE
menu icon not showning

### ISSUE THREAD

**Issue by pritam-kadam** [mikepenz/Android-ActionItemBadge#41]
In menu.xml i have set an icon to the menu item. But it doesn't show what i have set. It shows something else.

**Comment by mikepenz** [comment]
@pritam-kadam can you please show your menu.xml? Which icon? And what does it show? May also add a screenshot

**Comment by pritam-kadam** [comment]
This is how i added it into menu.xml

`<item
        android:id="@+id/actionNotification"
        android:icon="@drawable/ic_action_notification"
        app:actionLayout="@layout/menu_badge"
        app:showAsAction="always"
        android:title="Notification"/>`

I am using an action bar icon (i.e. ic_action_notification) that i generated using android image assets.

This is how i am using it in code:
`int badgeCount = 2;
        //you can add some logic (hide it if the count == 0)
        if (badgeCount > 0) {
            ActionItemBadge.update(this, menu.findItem(R.id.actionNotification), FontAwesome.Icon.faw_android, ActionItemBadge.BadgeStyles.RED, badgeCount);
        } else {
            ActionItemBadge.hide(menu.findItem(R.id.actionNotification));
        }
`

Actionbar Icon looks something like this:

![screenshot_2016-02-19-13-07-22](https://cloud.githubusercontent.com/assets/14782060/13169312/8bade3f6-d70a-11e5-9d81-342c83ef89d2.png)

**Comment by mikepenz** [comment]
Do you have a `assets/fonts` folder in your project? Seems like the font *.ttf file can't be resolved. Do you see some log output?

**Comment by pritam-kadam** [comment]
@mikepenz even that doesn't seem to make it work.

**Comment by mikepenz** [comment]
@pritam-kadam no that was a question. Some people have an `assets/Fonts` folder with an upper case letter and then it can't resolve the assets. 

Do you have any log output?

**Comment by pritam-kadam** [comment]
@mikepenz no I didn't see anything in logcat related to badge.

**Comment by mikepenz** [comment]
@pritam-kadam you should see something regarding font. or typeface or similar. 

Do you use proguard here? 
And you are sure you do not have a folder named `assets/fonts/` or so?

**Comment by pritam-kadam** [comment]
@mikepenz in logcat i am seeing nothing. Using proguard only for release apk. and i have folder named assets/font and fontello.ttf & materialdrawerfont.ttf in it.

**Comment by mikepenz** [comment]
@pritam-kadam may you can send me a sample showcasing the issue and I can debug it?
