### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by localhostEU** [mikepenz/Android-ActionItemBadge#43]
Version 3.2.3, Android 6 (Genymotion)

```
java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.GradientDrawable
                                                                       at com.mikepenz.actionitembadge.library.utils.BadgeDrawableBuilder.build(BadgeDrawableBuilder.java:39)
```

**Comment by mikepenz** [comment]
@localhostEU thanks. Will have to check this. Really weird that they just changed the class...

https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/res/drawable/badge.xml

You have not overwritten this right?

**Comment by mikepenz** [comment]
i renamed the resources in the latest version. perhaps this fixes your issue

**Comment by localhostEU** [comment]
It works :+1:

**Comment by mikepenz** [comment]
@localhostEU ok seems some other library you used conflicted with the `badge.xml`
