### ISSUE TITLE
change badge direction from right to left

### ISSUE THREAD

**Issue by RezaOruji** [mikepenz/Android-ActionItemBadge#46]
hi mike. thank you for your another great library.
is there any way to change the badge direction in the MenuItem from right to left ?
 i want to use it in a RTL application .

**Comment by mikepenz** [comment]
@RezaOruji you want the badge on the left side? 

Not out of the box, but if you provide an RTL version of the following layout in your application it should be used autommatically:
https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/res/layout/menu_action_item_badge.xml
(copy it to your project into the RTL folder and change it to look correctly)

**Comment by mikepenz** [comment]
Is this solution working? Just asking so I can close this issue
