### ISSUE TITLE
how can I add a border on badge??

### ISSUE THREAD

**Issue by MaxCavalheiro** [mikepenz/Android-ActionItemBadge#48]

**Comment by mikepenz** [comment]
@MaxCavalheiro sorry this is not possible. And there are no plans to add it. 

Here's the place where I create the `Drawable` 
https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/java/com/mikepenz/actionitembadge/library/utils/BadgeDrawableBuilder.java#L37
