### ISSUE TITLE
rounded corners example [example / documentation]

### ISSUE THREAD

**Issue by AndreiD** [mikepenz/Android-ActionItemBadge#49]
Thank you for the nice library.
Can you put an example how to make it with round corners ? I've tried but didn't succeed :(

**Comment by mikepenz** [comment]
@AndreiD nothing special about it. You just define the corner in pixel:
```java
ActionItemBadge.BadgeStyles.GREY_LARGE.getStyle().setCorner(UIUtil.convertDpToPx(ToolbarActivity.this, 12))
```
(using one of the provided styles as base)

Or you can also just create your own style 
```java
new BadgeStyle(BadgeStyle.Style.LARGE, R.layout.menu_action_item_badge_large, Color.parseColor("#e0e0e0"), Color.parseColor("#c7c7c7"), Color.BLACK).setCorner(UIUtil.convertDpToPx(ToolbarActivity.this, 12)
```

if you want a rounded badge just define the corner in pixel as the half of the height of the element
```java
.setCorner(UIUtil.convertDpToPx(ToolbarActivity.this, 12)
```

so 12 dp for a 24dp height badge.

**Comment by AndreiD** [comment]
Doesn't work if it's very small. I'm attaching a picture
No matter how I try to put the corner parameter, it still shows a rounded rectangle instead of a circle. 

![capture](https://cloud.githubusercontent.com/assets/542665/17509480/c1e74f26-5e22-11e6-96de-1381129d8995.JPG)

**Comment by mikepenz** [comment]
@AndreiD in this case it wouldn't work as the content is bigger than the possible radius can be.

**Comment by AndreiD** [comment]
yes. this is the case.  however I don't know how to fix it :(. it's a menu item image.

**Comment by mikepenz** [comment]
You could just use the layout I define in this lib and replace the flexible drawable I define with a real one. So you can do the same without using the lib
