### ISSUE TITLE
getDrawable improve

### ISSUE THREAD

**Issue by amorenew** [mikepenz/Android-ActionItemBadge#50]
hi
you use this method **UIUtil.getCompatDrawable** to avoid deprecated method
you can simply use **ResourcesCompat.getDrawable(getResources(),R.drawable.logo,null)** 
thanks

**Comment by mikepenz** [comment]
@amorenew perhaps I will remove this method as the compat libs now have already all those great helper methods out of the box ;)

Thanks for pointing this out. You may also open a PR with doing this change if you want
