### ISSUE TITLE
Problem with buildToolsVersion 24.0.0

### ISSUE THREAD

**Issue by tentypwtk** [mikepenz/Android-ActionItemBadge#51]
ActionBar icon with "layout/menu_action_item_badge" added works fine with 23.0.3, but on 24.0.0 it doesn't show up at first (empty square). Only after adding a badge it draws correctly the item.

edit: Looks like I jumped to conclusions too quickly. Looks like it doesn't make any difference which version I use. I added ActionItemBadge.update at the end of onCreateOptionsMenu and seems to work. Without that it's just an empty space.

**Comment by mikepenz** [comment]
That's correct you have to do something programatically too.
