### ISSUE TITLE
disappearing badge on toolbar

### ISSUE THREAD

**Issue by usergoodvery** [mikepenz/Android-ActionItemBadge#57]
Hi,
Firstly, thanks for sharing this useful lib. 
I have a standard menu file where I am displaying two items set as app:showAsAction="always", one of which is actionitem badge and other is a textview.  The value of the badge is updated via (a sticky) async event (greenrobot). That works fine, except when I press the overflow menu   the badge disappears, but its place holder remains empty. The text view doesn't have this issue.
Is there anything that i could be missing there?

regards

**Comment by mikepenz** [comment]
@usergoodvery that sounds weird, can you reproduce this in the sample?

**Comment by usergoodvery** [comment]
I think I traced down the issue and luckily it is unrelated to the library, so you are off the hook :)

BTW can this lib be used with non actionitems, an it work with icons placed elsewhere other than toolbar??

**Comment by mikepenz** [comment]
Awesome :)

Sadly no. As it is written for the `Toolbar` and adjusts the layout for these items.
