### ISSUE TITLE
Remove badge on Run time using fragment 

### ISSUE THREAD

**Issue by vinayaksrs** [mikepenz/Android-ActionItemBadge#58]
Hi,  
Thanks for the awesome library.  How can I remove only badge on runtime but not hiding entire menu item in fragment. 

Thanking you in advance for your time

**Comment by praneethrahul** [comment]
Below code might help you.

ActionItemBadge.update(DashBoardActivity.this, menuThis.findItem(R.id.action_notifications), UIUtil.getCompatDrawable(MainActivity.this, R.mipmap.ic_action_notification_icon),
                    ActionItemBadge.BadgeStyles.TRANSPARENT, NumberUtils.formatNumber(badgeDrawableCount));

**Comment by vinayaksrs** [comment]
ActionItemBadge.BadgeStyles.TRANSPARENT  and UIUtil.getCompatDrawable(MainActivity.this, R.mipmap.ic_action_notification_icon) are  not included in the latest libray

**Comment by mikepenz** [comment]
@vinayaksrs if I correctly remember, this is shown in the sample app

**Comment by vinayaksrs** [comment]
Nope. I checked the whole library. But i couldn't find  ActionItemBadge.BadgeStyles.TRANSPARENT and UIUtil.getCompatDrawable(MainActivity.this, R.mipmap.ic_action_notification_icon).    So I am using  ActionItemBadge.hide() for now. 

UIUtil.getCompatDrawable(MainActivity.this, R.mipmap.ic_action_notification_icon) this functionality removed from latest version 3.3.1

**Comment by mikepenz** [comment]
Hiding the badge is shown here: https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/app/src/main/java/com/mikepenz/actionitembadge/sample/MainActivity.java#L51

**Comment by vinayaksrs** [comment]
@mikepenz  ActionItemBadge.hide(), this method removes the icon from menu. I don't want to remove icon. I just  want to remove badge only.

This is my scenario, I am showing notification icon in the toolbar menu with unread notification count as badge. When unread notification count become 0, I want to remove the badge but not the menu icon.

**Comment by mikepenz** [comment]
@vinayaksrs set the `BadgeCount` to `null` and the badge will hide

**Comment by vinayaksrs** [comment]
It worked.. Thank You
