### ISSUE TITLE
How i can make ActionItemBadge.BadgeStyles smaller.

### ISSUE THREAD

**Issue by trinhvanminh2009** [mikepenz/Android-ActionItemBadge#60]
I so love this library . But how I can make ActionItemBadge.BadgeStyles smaller. I have 2 options, 1 is normal, 1 is large. I want another option is small ? How can I do that ?
Thanks

**Comment by mikepenz** [comment]
@trinhvanminh2009 well the lib only comes with those 2 styles. 
If you want a completely other style you have to do it manually. Define your own layout: https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/res/layout/menu_action_item_badge.xml (like this) 
And then define your own style:
https://github.com/mikepenz/Android-ActionItemBadge/blob/321b45a65c258e8e1e9346f16d0c80152c6af9d8/library/src/main/java/com/mikepenz/actionitembadge/library/ActionItemBadge.java#L28

**Comment by trinhvanminh2009** [comment]
Thank you. I know what I have to do.
