### ISSUE TITLE
Appbar Icon Disappears After Update

### ISSUE THREAD

**Issue by frankodoom** [mikepenz/Android-ActionItemBadge#61]
Hello my Appbar Icon Disappears after i update it!

```
@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.app_bar_main, menu);

        int badgeCount =5;

        if (badgeCount > 0) {
            ActionItemBadge.update(this, menu.findItem(R.id.notify_me), (Drawable) Iconics.findFont(this,"Fontawesome"), ActionItemBadge.BadgeStyles.RED, badgeCount);
        } else {
            ActionItemBadge.hide(menu.findItem(R.id.notify_me));
        }
        return super.onCreateOptionsMenu(menu);
    }
```

**Comment by mikepenz** [comment]
@frankodoom you are sure it's running into `update` and not `hide`?

**Comment by frankodoom** [comment]
@mikepenz  it runs the update not hide, in your XML what are you referencing as `actionLayout, is it an ImageView ?`

**Comment by frankodoom** [comment]
i run into update i see the badger alright but my Menu Item becomes hidden, looking at the Xml in your documentation what becomes :actionLayout ?

**Comment by mikepenz** [comment]
well the actionLayout is something the android framework provides to allow modifying the xml used to display in the toolbar

**Comment by mikepenz** [comment]
@frankodoom I see no reason why this happens. please refer to the sample app. if this does not help. please re-open and provide a open-able sample application which allows me to re-produce this
