### ISSUE TITLE
I would like to show the badge number on android.support.design.widget.BottomNavigationView

### ISSUE THREAD

**Issue by Jinqianv** [mikepenz/Android-ActionItemBadge#62]
BottomNavigationView bottomNavigationView = (BottomNavigationView) findViewById(R.id.bottom_navigation);
        bottomNavigationView.setSelectedItemId(R.id.connect);
        //bottomNavigationView.setItemIconTintList(null);
        BottomNavigationViewHelper.disableShiftMode(bottomNavigationView);

        int badgeCount = 5;
        Menu menu = bottomNavigationView.getMenu();
        MenuItem messagesItem = menu.findItem(R.id.Messages);
        App.messagesItem = messagesItem;
        if (badgeCount > 0) {
            ActionItemBadge.update(this, messagesItem, ResourcesCompat.getDrawable(getResources(), R.drawable.ic_chat, null), ActionItemBadge.BadgeStyles.RED, badgeCount);
        } else {
            ActionItemBadge.hide(messagesItem);
        }

The badge number is not showing.
Please help me.

**Comment by mikepenz** [comment]
@Jinqianv this library only supports Toolbar's and ActionBar'S
