### ISSUE TITLE
How to make the icon not increase in size,

### ISSUE THREAD

**Issue by dev12-SC** [mikepenz/Android-ActionItemBadge#63]
How to make the icon not increase in size,
the two examples have the ic_notifications_white_36dp icon, but when I use ActionItemBadge, update (.., .., getDrawable (R.mipmap.ic_notifications_white_36dp), ActionItemBadge.BadgeStyles.RED, 1) the icon gets bigger.
  Is there any way to make the icon using update () get the original size?
![screenshot_1505924668](https://user-images.githubusercontent.com/15039214/30655802-654da8ba-9e08-11e7-8d26-5baf61b15750.jpg)

@mikepenz Your jobs are greats, congratulation.

**Comment by mikepenz** [comment]
You will have to adjust this layout and change the sizings. 
https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/res/layout/menu_action_item_badge.xml
(probably the ImageView should not use the default scaleType)

**Comment by dev12-SC** [comment]
@mikepenz Tanks

**Comment by fukemy** [comment]
hi, anyway to do it without modify library? Thanks
