### ISSUE TITLE
Proguard breaking builds

### ISSUE THREAD

**Issue by AdityaAnand1** [mikepenz/Android-ActionItemBadge#65]
```
Warning:com.mikepenz.actionitembadge.library.ActionItemBadge: can't find referenced class com.mikepenz.iconics.IconicsDrawable
Warning:com.mikepenz.actionitembadge.library.ActionItemBadge: can't find referenced class com.mikepenz.iconics.typeface.IIcon
Warning:com.mikepenz.actionitembadge.library.ActionItemBadgeAdder: can't find referenced class com.mikepenz.iconics.IconicsDrawable
Warning:com.mikepenz.actionitembadge.library.ActionItemBadgeAdder: can't find referenced class com.mikepenz.iconics.typeface.IIcon
```

Perhaps optimal rules can be bundled in the library itself?

**Comment by mikepenz** [comment]
@AdityaAnand1 as far as I can tell it should not be a problem that the `IconicsDrawable` is obfuscated. 

Do you have https://github.com/mikepenz/Android-Iconics in your project? 
Do you use it? if not you might just add `-dontwarn com.mikepenz.iconics.*`

**Comment by AdityaAnand1** [comment]
Yeah, I figured as much. Still, adding that rule to the library's consumerProguardFile (or whatever it's called) would mean all of us don't have to 😄

**Comment by mikepenz** [comment]
A general `warn` would be not good :) 

Great that it works
