### ISSUE TITLE
No way to remove badge.

### ISSUE THREAD

**Issue by ChaosPower** [mikepenz/Android-ActionItemBadge#66]
Hi,

Currently there is no option to hide just the badge. If there is a work around this please inform me.

Thanks!

**Comment by mikepenz** [comment]
Passing in `null` as `badge` content will remove the badge.

**Comment by ChaosPower** [comment]
Thanks @mikepenz will try it out!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/java/com/mikepenz/actionitembadge/library/ActionItemBadge.java#L229

**Comment by ChaosPower** [comment]
Hi @mikepenz 

I have set `badgeCount = null` however, the icon does not show.

![screenshot_1520956463](https://user-images.githubusercontent.com/260845/37353405-3d3be490-271a-11e8-9d66-e20f5249a7bf.png)

Thanks!

**Comment by mikepenz** [comment]
So you want to only remove the badge?

There is no api for that. if you want to have no badge replace it with a normal MenuItem
