### ISSUE TITLE
Can I add this to appear on the top right of an exising imageView?

### ISSUE THREAD

**Issue by hamzabinamin** [mikepenz/Android-ActionItemBadge#67]
Can I add this to appear on the top right of an existing imageView? or use my own image with the item?

**Comment by mikepenz** [comment]
No this library is not meant to do this. You might find a different library to serve this purpose. sorry.

**Comment by hamzabinamin** [comment]
@mikepenz  Currently the android doodle appears with the counter shouldn't there be an option to use your own image?

**Comment by mikepenz** [comment]
This library is only meant for the toolbar. 
Look at the sample showcase how it's used. 

The normal icon is there, and in addition it can have the number
