### ISSUE TITLE
Long press on action icon does not show tooltip with action name

### ISSUE THREAD

**Issue by deinlandel** [mikepenz/Android-ActionItemBadge#7]
For "regular" action bar buttons, when I long press the button , a tooltip with action title (android:title from item in menu xml) is shown. 

But for action bar buttons with badge (when android:actionLayout="@layout/menu_badge" is used), this behavior is broken - no tooltip is shown on long press.

**Comment by mikepenz** [comment]
Doesn't seem to be possible

**Comment by fernando-chileno** [comment]
This may help in meanwhile: https://gist.github.com/romannurik/3982005
Then you get the action view from the menu item
