### ISSUE TITLE
How to choose the badge backcolor?

### ISSUE THREAD

**Issue by jrcacd** [mikepenz/Android-ActionItemBadge#72]

**Comment by mikepenz** [comment]
This lib is no longer actively developed. but the approach was by providing the `BadgeStyle`

https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/java/com/mikepenz/actionitembadge/library/utils/BadgeStyle.java

**Comment by jrcacd** [comment]
Ok, thanks. I really need to change it dynamically.
