### ISSUE TITLE
Can't find  class file for com.mikpenz.iconics.typeface.IIcon not found

### ISSUE THREAD

**Issue by stonyz** [mikepenz/Android-ActionItemBadge#8]
I used the latest Android studio to try it, but get the following error,

added 2 dependencies 

> compile 'com.joanzapata.android:android-iconify:1.0.8'
>     compile 'com.mikepenz.actionitembadge:library:2.0.0@aar'

Error:(48, 28) error: cannot access IIcon
class file for com.mikpenz.iconics.typeface.IIcon not found

**Comment by chnouman** [comment]
still getting same error
