### ISSUE TITLE
Is there a way to simply show the un-badged icon?

### ISSUE THREAD

**Issue by somghosh** [mikepenz/Android-ActionItemBadge#9]
It seems from readme, and when I tried out that I can just update to a given badge or hide the icon in menu completely - is there a way to show the normal icon without a badge?

thanks

**Comment by mikepenz** [comment]
@somghosh you can simply pass -1 as badge value. This will hide the badge. 

If you don't need the badge functionality you can use this library: https://github.com/mikepenz/Android-Iconics and set the drawable for an actionItem. (This is used internally by ActionItemBadge)

**Comment by mikepenz** [comment]
@somghosh is this still a problem? i will close this issue now, you can still reopen it if you answer here and there are still some issues.

**Comment by aacanakin** [comment]
Hello,
I passed the badgeCount as -1 but it doesn't seem to work;
```java
        if (mNotificationCount > 0) {
            ActionItemBadge.update(this, menu.findItem(R.id.action_notification),
                    FontAwesome.Icon.faw_bell, ActionItemBadge.BadgeStyles.RED, mNotificationCount);
        } else {
            ActionItemBadge.update(this, menu.findItem(R.id.action_notification),
                    FontAwesome.Icon.faw_bell, ActionItemBadge.BadgeStyles.RED, -1);
        }
```

**Comment by mikepenz** [comment]
@aacanakin this answer is from a previous version. with the latest version you can hide a badge like this:

```java
            ActionItemBadge.hide(menu.findItem(R.id.item_sampleBadge_drawable));
```

**Comment by aacanakin** [comment]
The code you just sent hides the menu. I don't want to hide the menu. I want to hide the badge

**Comment by mikepenz** [comment]
Oops sorry. i mixed things up. Hiding a Badge is now possible via Integer.MIN_VALUE

https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/app/src/main/java/com/mikepenz/actionitembadge/sample/ToolbarActivity.java#L105

**Comment by aacanakin** [comment]
OK. It's working. Thanks!
